services:
  - type: web
    name: docling-parser
    env: docker
    plan: free
    region: oregon
    branch: main
    repo: https://github.com/darth-divyansh/Fast_API_DoclingServer
    dockerContext: .
    envVars:
      - key: PORT
        value: 8000
